In [12]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import matplotlib.pyplot as plt


df = pd.read_csv("homeprices.csv")
print(df)



import math
median_badrooms = math.floor(df.bedrooms.median())
median_badrooms

df.bedrooms = df.bedrooms.fillna(median_badrooms)
df


reg =  linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df.price)

m= reg.coef_
print(m)
# [  112.06244194 23388.88007794 -3231.71790863]

b= reg.intercept_
print(b)
# 221323.0018654043


# task1 
reg.predict([[3000,3,40]])
# array([498408.25158031])

Y =  112.06244194*3000 + 23388.88007794*3 + -3231.71790863*40 + 221323.0018654043
print(Y) #[498408.2515740243]


# task1 
reg.predict([[2500,4,5]])
# array([578876.03748933])

Y =  112.06244194*2500 + 23388.88007794*4 + -3231.71790863*5 + 221323.0018654043
print(Y) #[578876.0374840144]





# %matplotlib inline
# plt.xlabel('area(sqr ft)', fontsize=20)
# plt.ylabel('price(US$)' , fontsize=20 )
# plt.scatter(df.area,df.price,color='red',marker='+')

# reg.predict([[3300]])
# print(reg.predict([[3300]]))

# m= reg.coef_

# b= reg.intercept_

# Y = m*3300 + b 
# print(Y) #[628715.75342466]

# %matplotlib inline
# plt.xlabel('area', fontsize=20)
# plt.ylabel('price' , fontsize=20 )
# plt.scatter(df.area,df.price,color='red',marker='+')
# plt.plot(df.area,reg.predict(df[['area']]),color='blue')


   area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000
[  112.06244194 23388.88007794 -3231.71790863]
221323.0018654043
498408.2515740243
578876.0374840144


c:\Users\MO\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
c:\Users\MO\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
