In [19]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from word2number import w2n
import matplotlib.pyplot as plt


df = pd.read_csv("hiring.csv")
print(df)

df.experience = df.experience.fillna("zero")
df


df.experience = df.experience.apply(w2n.word_to_num)
df


import math
median_tests= math.floor(df['test_score(out of 10)'].mean())
median_tests

df['test_score(out of 10)'] = df['test_score(out of 10)'].fillna(median_tests)
df



reg =  linear_model.LinearRegression()
reg.fit(df[['experience','test_score(out of 10)','interview_score(out of 10)']],df['salary($)'])

m= reg.coef_
print(m)
# [2922.26901502 2221.30909959 2147.48256637]

b= reg.intercept_
print(b)
#14992.65144669314


# task1 
reg.predict([[2,9,6]])
# array([53713.86677124])

# task2
reg.predict([[12,10,10]])
# import pandas as pd
import numpy as np
from sklearn import linear_model
from word2number import w2n
import matplotlib.pyplot as plt


df = pd.read_csv("hiring.csv")
print(df)

df.experience = df.experience.fillna("zero")
df


df.experience = df.experience.apply(w2n.word_to_num)
df


import math
median_tests= math.floor(df['test_score(out of 10)'].mean())
median_tests

df['test_score(out of 10)'] = df['test_score(out of 10)'].fillna(median_tests)
df



reg =  linear_model.LinearRegression()
reg.fit(df[['experience','test_score(out of 10)','interview_score(out of 10)']],df['salary($)'])

m= reg.coef_
print(m)
# [2922.26901502 2221.30909959 2147.48256637]

b= reg.intercept_
print(b)
#14992.65144669314


# task1 
reg.predict([[2,9,6]])
# array([53713.86677124])

# task2
reg.predict([[12,10,10]])
# import pandas as pd
import numpy as np
from sklearn import linear_model
from word2number import w2n
import matplotlib.pyplot as plt


df = pd.read_csv("hiring.csv")
print(df)

df.experience = df.experience.fillna("zero")
df


df.experience = df.experience.apply(w2n.word_to_num)
df


import math
median_tests= math.floor(df['test_score(out of 10)'].mean())
median_tests

df['test_score(out of 10)'] = df['test_score(out of 10)'].fillna(median_tests)
df



reg =  linear_model.LinearRegression()
reg.fit(df[['experience','test_score(out of 10)','interview_score(out of 10)']],df['salary($)'])

m= reg.coef_
print(m)
# [2922.26901502 2221.30909959 2147.48256637]

b= reg.intercept_
print(b)
#14992.65144669314


# task1 
reg.predict([[2,9,6]])
# array([53713.86677124])

# task2
reg.predict([[12,10,10]])
# array([93747.79628651])



  experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000
[2922.26901502 2221.30909959 2147.48256637]
14992.65144669314


c:\Users\MO\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
c:\Users\MO\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([93747.79628651])